### ISSUE TITLE
Sequence index must be integer

### ISSUE THREAD

**Issue by skiniemini** [modrzew/pokeminer#169]
Keep getting this errors:

```
Traceback (most recent call last):
  File "worker.py", line 129, in run
    self.main()
  File "worker.py", line 170, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: sequence index must be integer, not 'str'
```

Any quick fix for this?

**Comment by nern9** [comment]
I keep getting the same on 2 new accounts. Running on latest forts branch

**Comment by nern9** [comment]
i found this error message when i scrolled up a bit above the error: `ERROR][L  88] Could not retrieve token: As a security measure, your account has been disabled for 15 minutes because you have failed to log in correctly too many times. Please come back and try again in 15 minutes.`

go and see if you are having problem loging in with the accounts you are using. if this is so, make sure you have the right password defined in config.py

**Comment by skiniemini** [comment]
I turned on debug logging and have been going through the log. Looks like they might be related to an account login/activation issue. I've been going through and figuring out what accounts are having issues so I can fix them. Once I have all the accounts sorted out, I'll see if it still gives the save error.

**Comment by skiniemini** [comment]
**Update:** After correcting the issues with the problem accounts (activation, valid accounts, etc), the error does not show up anymore.
