### ISSUE TITLE
[suggestion] different base layer for heatmaps

### ISSUE THREAD

**Issue by Aiyubi** [modrzew/pokeminer#190]
first: I am colorblind
Seeing the heatmaps there are a lot of the same colors (city) - yellow to red for heat and orange(?) for streets and such. All bright colors.

I coded myself so my local version uses satellite basemap as a quick fix. But for a wishlist I would like a darker basemap that can be chosen via config

Possible very dark map layer:
https://carto.com/location-data-services/basemaps/
dark matter map (second pic and below some code I found)

**Comment by YonderGod** [comment]
Are reports still using google maps? If they're still google, they will be leaflet soon, which has lots of different options. 
#186 
I suggested changing the main map too.

**Comment by Aiyubi** [comment]
yeah reports still run gmaps - and my request

**Comment by modrzew** [comment]
Note: *soon* means Soon™.

I found out that changing the tile layer in Leaflet is very easy (just change URL in one place). In the beginning I also thought of using grayscale map (to make Pokemon stand out more), but the Carto map requires an API key (which I don't want to use, due to all the hassle with Google Maps key and putting it in the config).

There's an existing discussion about maps provider in #186.
