### ISSUE TITLE
Number of steps!?

### ISSUE THREAD

**Issue by elx0r** [modrzew/pokeminer#54]
I just started running an area using 156 workers and it takes 20-30mins x cycle.
I read that you can change number of steps or smthg like that...How can I do that? Thank you

**Comment by Aiyubi** [comment]
again:
check the readme again. Lat/Long gain is the distance between points.

**Comment by elx0r** [comment]
I learned what that was mate...but I don't see the connection between steps and distance from one point to another  O.o
The readme doesn't explain that part at all...it just gives you lat gain and long gain with a random nr after without even explaining how "much" 0,0015 is

**Comment by modrzew** [comment]
Number of steps was dropped some time ago, now workers visit all points of interest in their area. You can configure the spread of the points by lat/lon gains.

How much it is depends on where you are. One degree of longitude is about ~110 km at equator and decreases to 0 as you go to either of the poles. There isn't any mechanism in pokeminer for calculating that, because you usually set it up once and forget about it, so my opinion is you can do the math manually. And I'd rather focus on more interesting things, especially that I have already configured parameters for my city :wink:

Feel free to open pull request with such enhancement if you happen to write it.
